"""pi_agent: Agent runtime (Python port of @earendil-works/pi-agent-core)."""

from pi_agent.agent import (
    Agent,
    AgentOptions,
    ActiveRun,
    PendingMessageQueue,
)
from pi_agent.agent_loop import (
    agent_loop,
    agent_loop_continue,
    execute_tool_calls,
    prepare_tool_call,
    run_agent_loop,
    run_agent_loop_continue,
    stream_assistant_response,
)
from pi_agent.messages import (
    BRANCH_SUMMARY_PREFIX,
    BRANCH_SUMMARY_SUFFIX,
    COMPACTION_SUMMARY_PREFIX,
    COMPACTION_SUMMARY_SUFFIX,
    AgentMessage,
    BashExecutionMessage,
    BranchSummaryMessage,
    CompactionSummaryMessage,
    CustomMessage,
    bash_execution_to_text,
    convert_to_llm,
    create_branch_summary_message,
    create_compaction_summary_message,
    create_custom_message,
)
from pi_agent.compaction import (
    CompactionPreparation,
    CompactionResult,
    CompactionSettings,
    DEFAULT_COMPACTION_SETTINGS,
    compact,
    estimate_context_tokens,
    find_cut_point,
    find_turn_start_index,
    generate_summary,
    prepare_compaction,
    should_compact,
)
from pi_agent.harness import (
    AgentHarness,
    BeforeAgentStartContext,
    HOOK_NAMES,
    HarnessContext,
    HarnessRunResult,
    NavigationResult,
    SessionCompactContext,
    SessionFlushContext,
    SessionNavigateContext,
)
from pi_agent.types import (
    AfterToolCallContext,
    AfterToolCallResult,
    AgentContext,
    AgentEvent,
    AgentLoopConfig,
    AgentLoopTurnUpdate,
    AgentState,
    AgentTool,
    AgentToolCall,
    AgentToolResult,
    AgentToolUpdateCallback,
    BeforeToolCallContext,
    BeforeToolCallResult,
    PrepareNextTurnContext,
    QueueMode,
    ShouldStopAfterTurnContext,
    StreamFn,
    ThinkingLevel,
    ToolExecutionMode,
)

__all__ = [
    # agent (2.3)
    "Agent",
    "AgentOptions",
    "ActiveRun",
    "PendingMessageQueue",
    # agent loop
    "agent_loop",
    "agent_loop_continue",
    "run_agent_loop",
    "run_agent_loop_continue",
    "stream_assistant_response",
    "execute_tool_calls",
    "prepare_tool_call",
    # messages
    "BRANCH_SUMMARY_PREFIX",
    "BRANCH_SUMMARY_SUFFIX",
    "COMPACTION_SUMMARY_PREFIX",
    "COMPACTION_SUMMARY_SUFFIX",
    "AgentMessage",
    "BashExecutionMessage",
    "BranchSummaryMessage",
    "CompactionSummaryMessage",
    "CustomMessage",
    "bash_execution_to_text",
    "convert_to_llm",
    "create_branch_summary_message",
    "create_compaction_summary_message",
    "create_custom_message",
    # compaction
    "CompactionPreparation",
    "CompactionResult",
    "CompactionSettings",
    "DEFAULT_COMPACTION_SETTINGS",
    "compact",
    "estimate_context_tokens",
    "find_cut_point",
    "find_turn_start_index",
    "generate_summary",
    "prepare_compaction",
    "should_compact",
    # harness
    "AgentHarness",
    "BeforeAgentStartContext",
    "HOOK_NAMES",
    "HarnessContext",
    "HarnessRunResult",
    "NavigationResult",
    "SessionCompactContext",
    "SessionFlushContext",
    "SessionNavigateContext",
    # types
    "AfterToolCallContext",
    "AfterToolCallResult",
    "AgentContext",
    "AgentEvent",
    "AgentLoopConfig",
    "AgentLoopTurnUpdate",
    "AgentState",
    "AgentTool",
    "AgentToolCall",
    "AgentToolResult",
    "AgentToolUpdateCallback",
    "BeforeToolCallContext",
    "BeforeToolCallResult",
    "PrepareNextTurnContext",
    "QueueMode",
    "ShouldStopAfterTurnContext",
    "StreamFn",
    "ThinkingLevel",
    "ToolExecutionMode",
]
